### ISSUE TITLE
Zombies: Deleted rems come back when using a different browser

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#211] opened 2020-10-20 11:36 UTC
**Describe the bug**
I have a Windows Desktop with Chrome and a Linux Laptop with Chrome and Firefox.
Yesterday I did a bunch of reorganizing and deleting on Windows Chrome and today I logged in with the Linux Firefox (it had an old RemNote state, maybe 2 weeks old). A lot of deleted rem were back and the hiding state of some headlines was wrong.

This is especially fustrating if you rewrite content and delete the old since you have duplicated content dispersed in your knowledge base.

**To Reproduce**
I don't know. This will probably hard to pin down. I can't even rule out that the Firefox hadn't fully synchronized before (but I'm pretty sure since I have the habit to wait for the sync complete notification before closing the tab and it was closed in firefox).

**Desktop (please complete the following information):**
 - Browser: Chrome (new state) and Firefox (old state)

**Additional context**
I made a backup randomly right before I opened Firefox on Chrome and then shortly after I began redeleting some rem.
I am not comfortable sharing a full backup (I don't remember how much personal stuff I already wrote), but I can share a diff.
It does not look helpful though, mostly updated `s` timestamps and said zombie rems being back.

I tried to import my old backup, but it did not work. See #210.

**Comment by hannesfrank** [comment] 2020-10-21 10:22
It can also mess up portals
![image](https://user-images.githubusercontent.com/4137110/96707034-a4c07d80-1397-11eb-80a4-973a0c0a60fb.png)

Left: the instance with an old state synced in. Right: A clean import of the raw json backup into a different account.

Note: I renamed `RemNote > Development` to `RemNote > RemNote Development` which got reverted by the sync.

(It might also be possible that this was caused by the import I tried in #210, but that felt like a noop so probably not.)

**Comment by hannesfrank** [comment] 2020-10-25 10:22
Aaargh, they are all back AGAIN! I now cleared the cache of all browsers I ever used so at least those particular rem should stay dead I hope.

I assume this is not as simple as "Hey let's sync those two states. Oh, I have a rem which id does not appear in the database. It must be new!"

I noticed that you redirect https://www.remnote.io/homepage to the queue now. Is there another way to clear the browser cache (in Chrome) before triggering a sync?

I think I have to use incognito tabs as a workaround for now to prevent these syncing problems. It is at least easier to do/remember than logging out and/or cleaning the cache. Sadly I have to remember to start up and sync an instance every time I might have to go offline.

**Comment by mfranzs** [comment] 2020-11-18 16:24
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!

**Comment by Eikosa** [comment] 2020-12-05 16:09
unfortunately the problem is not solved and it still happens

**Comment by a22a-dev** [comment] 2020-12-18 11:09
Yes it is happening with me too. Already done same thing three times. Begining to regreat moving from anki to remnote.

**Comment by mfranzs** [comment] 2021-01-07 23:23
I believe we've fixed the ultimate underlying cause now. Please let me know if you ever see this happen again.

**Closed** 2021-01-07 23:25 UTC
Labels: fixed-in-next-update
