### ISSUE TITLE
Two daily documents

### ISSUE THREAD

**Issue by webstert837** [remnoteio/remnote-issues#656] opened 2021-01-28 20:37 UTC
Yesterday I created a Daily Doc using alt-d.  When I looked today, I saw that it had created an additional daily doc.  There was already one there which has the standard portals at the bottom.  
![image](https://user-images.githubusercontent.com/70997646/106195489-d2c31400-6175-11eb-817e-4a18a636a9f3.png)

**To Reproduce**
I' afraid I have not been able to reproduce.  I do often have RemNote open on more than one computer or window.  

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by gregskupien** [comment] 2021-01-29 06:47
It also occurs in desktop app (Win 10). If today's daily document is already created pressing Alt + D will create a new one (duplicate).

**Comment by hannesfrank** [comment] 2021-01-29 12:04
Is this a duplicate of #611 ?

**Comment by mfranzs** [comment] 2021-01-29 22:16
Does the extra daily doc go away if you refresh, search for something, and wait a minute?

**Comment by SG60** [comment] 2021-01-29 22:32
This is happening to me also. I ended up with three for today. Not totally sure how to reproduce it.

I've only been using remnote on one device (Desktop client, Windows 10).

**Comment by gregskupien** [comment] 2021-01-30 07:10
> Does the extra daily doc go away if you refresh and then create a new reference to a date?

The opposite, another extra daily doc is created. So this happens when I refresh or open the desktop app for the first time, and hit Alt+D - always a new daily doc is created.
Btw. if I'm in the daily doc and refresh and hit Alt+D then a new one is not created. I have to be in different doc when I refresh.

![image](https://user-images.githubusercontent.com/50575574/106349921-38c4ae00-62d2-11eb-9562-38614a1d2897.png)

**Closed** 2021-02-03 20:10 UTC
Labels: fixed-in-next-update, fixed-in-remnote-1.2.2, priority=1
