### ISSUE TITLE
References to Concepts made out of other References are displayed like Descriptors and shows wrong Parent

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#71] opened 2020-08-30 05:07 UTC
**Describe the bug**
When I have a reference (**ref 1**) to a **Concept** and this **Concept** has a **Name** which is a reference (ref 2) to another **Stub**, then the **ref 1** will be displayed like **Parent Concept Rem > the Rem I am actually referring**  (Check the highlighted part in the screenshots) 

**To Reproduce**

1. Create a Rem hierarchy like in the screenshot.
2. Here  PC is a Parent Concept
3. CC is a Child Concept 
4. **Blah Test Stub 1** is a **Concept** and its **Name** is made out of two parts, the text '**Blah**' and reference to another **Stub** Rem **Test Stub 1**
5. Now if I try to create a reference to **Blah Test Stub 1** it shows the reference like **CC>Blah Test Stub 1** even though **Blah Test Stub 1** is a **concept**. 
6. If I change the name of **Blah Test Stub 1**  to just **Test Stub 1** then the reference looks like **PC>CC>Blah Test Stub 1**, which is more weird 

**Expected behavior**
The reference to **Blah Test Stub 1** should looks like **Blah Test Stub 1** (because it is a Concept) instead of **CC>Blah Test Stub 1**

**Screenshots**
![image](https://user-images.githubusercontent.com/24322880/91651576-50f28180-ea43-11ea-8d82-d679c4a946c3.png)
![image](https://user-images.githubusercontent.com/24322880/91651604-9e6eee80-ea43-11ea-92b3-39d794ddee59.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Version 2004
 - Browser: Chrome
 - Version: 84.0.4147.125 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Haven't tested

**Comment by tfiwm** [comment] 2020-08-30 17:25
This issue doesn't happen if **Test Stub 1** is of Type **Question**, to be specific the name should end with a question mark (?)

**Comment by tfiwm** [comment] 2020-11-10 02:43
Adding stubs to the equation makes things weird, but turns out stubs are not needed to reproduce this issue. This is some corner case issue while referencing rems that are under a **2 letter (or less) ** parent concept (really weird). If the parent Concept is longer than 2 letters, the issue doesn't happen. Check this GIF for details (all the time when the concept starts with an upper case letter the parent type here is Concept)
![rems_under_2letter_concept](https://user-images.githubusercontent.com/24322880/98620956-20d52380-22bb-11eb-8816-dd5e8c8dd6d3.gif)

**Comment by drkvj** [comment] 2021-04-05 09:02
@tfiwm thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now.

Both your queries are not actually bugs, but intended behaviours at this point. 

1. If a Rem ≤ 2 characters, then it will be shown in the hierarchy of the reference. We might change this behaviour, kindly comment your idea [here](https://github.com/remnoteio/remnote-issues/issues/10) .
2. The parent shown here seems to be correct, PC -> CC -> Test Stub 1 is the correct hierarchy. Also this behaviour has changed since then and all references of Rems that contain only references aren't shown similar to descriptors anymore. Rather they have multiple | before them to denote the level of reference. 

I am closing this issue for now, currently start relevant discussions on the Forum and I will be happy to explore these behaviours with you further (ping me there please)

**Closed** 2021-04-05 09:03 UTC
