### ISSUE TITLE
Help/Latest Updates → “Document deleted” 

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#1231] opened 2021-05-26 12:53 UTC
Navigating to Help/Latest Updates leads to “Document deleted”.

Happens only when I have Windowed Panes option enabled in Labs.

Related: https://forum.remnote.io/t/help-updates-document-deleted/4866

**Comment by talenelat-elin** [comment] 2021-05-26 12:59
Probably a duplicate of #1173

**Comment by hannesfrank** [comment] 2021-06-04 19:11
Thanks for the report @ognsya and the duplicate detection @talenelat-elin :) This should be fixed in v1.3.13.

**Closed by hannesfrank** 2021-06-04 19:11 UTC
Labels: duplicate
