### ISSUE TITLE
Huge bug in the scheduler 🔴 

### ISSUE THREAD

**Issue by drstrangez0** [remnoteio/remnote-issues#673] opened 2021-01-31 07:22 UTC
The scheduler is not working at all 
example 
This card created yesterday and I pressed "solid" Today I pressed "solid" again and still the interval is 24 hours instead of 3 days 
Its the same problem as #664 
 
![image](https://user-images.githubusercontent.com/70066742/106377460-2e77e200-63ae-11eb-89cb-fadc52fa68fb.png)
another examples
![image](https://user-images.githubusercontent.com/70066742/106377851-f32ae280-63b0-11eb-8360-d39b0bf607e0.png)

Turns out that I need to press solid in different 3 days just to make the interval 3 days 
Like the image shows the card appeared in **29,30,31** although I pressed "solid " each time 
Is this normal ????????????
![image](https://user-images.githubusercontent.com/70066742/106389959-255f3300-63f7-11eb-9232-8904ae6b4aec.png)

### explination 
**scheduler before the bug** 
day 1(solid -> +24 hours)
day 2( solid -> +3 days )
day 5 (solid -> +7 days)
**scheduler right now**
day 1(solid -> +24 hours)
day 2( solid -> +24 hours)
day 3 (solid -> +3 days)

**Comment by hugomarins** [comment] 2021-01-31 14:14
@drstrangez0 ,

Unfortunately, there is no a solid documentation on RemNote yet to explain how the algorithm works. Even though it is not accessible by the tutorials page (I can't understand why; I found it in a link in the Custom Schedulers settings), I found this link explaining Anki-SM2 scheduler.

https://www.remnote.io/documentation/Ab6Pp9gNgrMNZGTBM

It would be good if you could say whether you have set you schedule type to "Default" or "Anki SM-2".

![image](https://user-images.githubusercontent.com/54500828/106385940-72201b00-63b1-11eb-88d0-3b3ae8d9e51a.png)


There is no documentation about the Default type, so I wonder it must be very like Anki SM-2 but with the settings they think are ok for most cases (I suppose it is exactly equal Anki SM-2; if you want to use custom settings, so you will use Anki SM-2 and adjust learning steps, ease factor, maximum interval, and so on).

If you are using Anki SM-2, I have already noticed and published anomalous scheduling behavior in #639. I suppose they are working on it.

But if you are using the default type of settings, I will suppose (in the absence of documentation about it) that it must be very like what is shown when you first select Anki SM-2. It would be:

![image](https://user-images.githubusercontent.com/54500828/106385894-46049a00-63b1-11eb-9f9d-6223d23a17e9.png)

As you can see, the *Learning Phase* comprises 2 steps: 1 day, 2 days. As I understand it, if you answer Solid today in the first time you see the card, it will be shown tomorrow, yet in the learning phase. If you answer solid tomorrow, your card will "graduate" (using Anki terminology), and only then the so called "exponential phase" ("Revies" in Anki) will begin. Maybe (again I have to suppose in the absence of clear documentation) the behavior shown in the chart (below) only begin in the exponential phase.

![image](https://user-images.githubusercontent.com/54500828/106386324-22daea00-63b3-11eb-8873-e0eec43bf838.png)

Maybe it deliberately omits the first learning step, showing only the last one (the one that "graduates" the card to the Review or *Exponential Phase*).

Anyway, this 24h/24h interval doesn't seem so strange to me. For me it also happens, and I think it is ok:

![image](https://user-images.githubusercontent.com/54500828/106386504-05f2e680-63b4-11eb-8983-872f302ecf67.png)

How are the intervals behaving after this? This would be of greater importance.

**Comment by drstrangez0** [comment] 2021-01-31 15:04
> Default

My scheduler is default 
and I don't think this is normal because its the second time something like this happened and I end up with a +800 queue

**Comment by mfranzs** [comment] 2021-01-31 23:19
Thank you both for the clear discussion. 

I believe that this confusion is due to an upgrade in the scheduler to make it aware of the real world time interval between presses. The previous behavior here was that this interval would explode to multi-year intervals, violating the underlying SRS principles. 

We'll upgrade this chart to explicitly display the intervals to make this clearer. We'll also add that documentation link and work on making it more comprehensive.

This is assuming that that these were indeed practiced early. Were they practiced within a document in "All cards" mode?

**Comment by drstrangez0** [comment] 2021-02-01 04:58
> Thank you both for the clear discussion.
> 
> I believe that this confusion is due to an upgrade in the scheduler to make it aware of the real world time interval between presses. The previous behavior here was that this interval would explode to multi-year intervals, violating the underlying SRS principles.
> 
> We'll upgrade this chart to explicitly display the intervals to make this clearer. We'll also add that documentation link and work on making it more comprehensive.
> 
> This is assuming that that these were indeed practiced early. Were they practiced within a document in "All cards" mode?

is this scheduler normal??
day 1(solid -> +24 hours)
day 2( solid -> +24 hours)
day 3 (solid -> +3 days)

**Comment by SMerlock7** [comment] 2021-02-01 05:10
I was practicing from the queue(with spaced repetition) when this card appeared today. Can it appear earlier than the next repetition time? 
In addition; the previous interval was 19 days(on pressing easy), but this time the interval decreased to 7 days(on pressing solid). (Anki SM-2) I'm not sure if this is working as intended, although this is the only card that I found unusual after the recent upgrade till now.
![image](https://user-images.githubusercontent.com/75471109/106416709-0b196980-6478-11eb-95ff-904e6e826111.png)

**Comment by drstrangez0** [comment] 2021-02-01 09:23
This card appeared every day although that I answered correctly how is this normal ??????
![image](https://user-images.githubusercontent.com/70066742/106438986-402db800-6488-11eb-99de-19cada4c1009.png)

**Comment by hugomarins** [comment] 2021-02-01 13:05
@drstrangez0 Yes, this in not ok.

**Comment by hugomarins** [comment] 2021-02-02 09:07
@mfranzs Definitely the scheduler is not working as intended. I'm facing now the same problem as @drstrangez0, as shown below:

![image](https://user-images.githubusercontent.com/54500828/106576871-66049c80-651c-11eb-8515-e4598cb8f1b5.png)

The scheduler is stuck in a hell loop scheduling. Even though I rated the card "Solid" 3 times (in 3 subsequent days), the next repetition time is still stuck in 24h.

**Comment by drstrangez0** [comment] 2021-02-02 09:51
@hugomarins see bug #695 I found the cause

**Comment by mfranzs** [comment] 2021-02-03 03:58
Thank you all for helping to debug this. There was an edge case where the repetition could incorrectly be marked as "early" if it happened it happened only shortly before the card was scheduled. This will be fixed in the next update.

**Closed** 2021-02-03 20:10 UTC
Labels: fixed-in-next-update, fixed-in-remnote-1.2.2, priority=1
