### ISSUE TITLE
Automatic prefix search bug

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#34] opened 2020-08-10 05:10 UTC
**Describe the bug**
The automatic prefix search doesn't bring up the results of the siblings , it only brings the results of all the descendants of siblings 

**To Reproduce**
1. Go to any rem that has a few siblings with their own descendants
2. start a new rem and start typing the starting letter of any sibling rem 
3. Scroll down the search box and u will not find any siblings there , only the descendants will be there

**Expected behaviour**
Yes its great that all the descendants are being shown , but the siblings need to be as well . When a letter is typed , first preference needs to be given to the siblings at the current rem level and then followed by the nephews/nieces 

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser : chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version : 84.0.4147.105

**Comment by mfranzs** [comment] 2020-08-11 22:00
Thanks for the report. Are the siblings included in the current document that you're editing? If so, they won't be suggested in the automatic prefix search (the only Rem that appear in the hidden prefix search are hidden Rem.)

I cannot reproduce the problem when the siblings are hidden, so I'm tentatively closing this. Please re-open with a screenshot if you're still having problems!

**Closed by mfranzs** 2020-08-11 22:00 UTC
