### ISSUE TITLE
The back card of a descriptor rem directly under a document asks for document name instead of the Rem name

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#64] opened 2020-08-23 17:12 UTC
**Describe the bug**
When a **descriptor rem** is created directly under a **document** type rem and the **backwards practice** is enabled, the backward practice card asks for the **Name** of the parent document instead of the **Name** of the descriptor (Check the screenshot). This doesn't happen if the rem is of **Concept** type 

**To Reproduce**

1. Steps to reproduce the behavior:
2. Create a rem and tag that as a document (e.g. Mydoc)
3. Zoom into that document rem
4. Create another descriptor rem (e.g. mydesc) under this **Mydoc**
5. Enable **Backwards practice** on **mydesc**
6. Now check the cards preview at the bottom, you will see it like how it is in the attached screenshot. I.e. instead of asking **mydesc**'s name in the backwards card, **Mydoc**'s name is being asked.
7. Also, if you actually review the cards, you will see the backcard just like the how it appears in the card preview

**Expected behavior**
The backwards card for **mydesc** should ask for (or hide) the **Name** of **mydesc** instead of the **Name** of **Mydoc**

**Screenshots**
This is how is shows up in the cards preview
![image](https://user-images.githubusercontent.com/24322880/90984279-ca144500-e528-11ea-8e52-6752ccd284e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, version 2004
 - Browser: Chrome 
 - Version: 84.0.4147.125 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Haven't tested in smartphone

**Additional context**
NA

**Comment by tfiwm** [comment] 2020-08-23 18:34
I guess this is a change in behavior, please check the discussion here 
https://discord.com/channels/689979930804617224/722840095001935902/747154628638146560

**Comment by mfranzs** [comment] 2020-08-24 04:26
Thanks for the report. This sounds like indented behavior - the backward card for a descriptor asks you for the parent's name. Were you seeing differently before?

Although I was not aware of one, I apologize if there was indeed a bug here previously and your workflow was interrupted. One fix would be to change these descriptors to Concepts.

Closing for now as this is intended behavior.

**Closed by mfranzs** 2020-08-24 04:26 UTC
