### ISSUE TITLE
Non-expanded Portals don‘t show in queue

### ISSUE THREAD

**Issue by MarcWiem** [remnoteio/remnote-issues#511] opened 2021-01-10 18:52 UTC
Hi,
I have encountered a problem inside of my folders/documents. For example, if I have a portal inside document A to the document B, and this portal is not fully expanded (like with cmd + shift + ↓) then it won‘t add the cards (from document B) out of the portal to the queue of document A.
Is there a way to fully embed Information of B into A‘s queue without always expanding the portals?
I really hope you can help me, I‘m rather desperate right now.

Kind regards
Marc

**Comment by mfranzs** [comment] 2021-01-15 04:02
Thanks for reaching out. This is working as intended - only visible Rem are included in your queue. What are you trying to achieve here?

**Comment by MarcWiem** [comment] 2021-01-15 14:15
Thanks for the answer. First, I want to tell you I love RemNote and everything you’re doing to improve the app. I haven’t been a user for long, only a couple of months really, so I’m rather inexperienced in this field. I‘m studying and some of my classes are overlapping in specific topics so I need to learn the same things in both classes (which are sorted in different folders). So I have (many) portals from one class to the other, to only learn this stuff once, but I’m learning specifically in the class folder (“A“) , that has the portals in it, because this will be the upcoming test. Now when I‘m learning the queue from folder A I have to open every single portal, which is a little „laborious“. I don’t want to learn from document B (the class, in which I don’t write the test), because it has lots of other information that I don’t need. Is it possible that you could add a feature, to turn the „hidden-portal cards“ to the queue (voluntarily in the settings maybe)? I think that‘d be great, or is there a better work around / organisation tactic?
Kind regards, 
Marc
(PS: I‘m sorry for the long text, and the mistakes I probably made, but English isn’t my first language)

**Comment by drkvj** [comment] 2021-04-16 08:32
Hey @MarcWiem thanks for getting in touch, closing this as it is not a bug report. 
Additionally you might get more inputs regarding questions of this sort from the community, either in discord or the forum. 
Good luck, hope you are enjoying RemNote!

**Closed by drkvj** 2021-04-16 08:32 UTC
Labels: working-as-intended
