### ISSUE TITLE
Format Rems as per the rem type ( concept, descriptor etc.) even when there is no :: (name - content separator) 

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#109] opened 2020-09-17 05:36 UTC
**Is your feature request related to a problem? Please describe.**
Only when the rem is generating a card, specifically when the rem has **name** and **content** separated by **::** symbol the formatting based on rem type takes effect. By formatting I mean, Concepts having bold text and descriptors having italicized text etc. By default a new Rem doesn't have any type, but setting a Rem to a specific type using the bottom toolbar or a keyboard shortcut or command should make the formatting according to the set type

**Describe the solution you'd like**
When I set a Rem to a specific type, the Rem should follow the formatting rules for that particular type even when there is no **name** **content** separation using the **::** Symbol. E.g. if I set a Rem to a Concept type, that Rem should be in bold text (specifically the Rem should inherit the styling from the CSS class for concept names)

**Describe alternatives you've considered**
Alternative is to put an ending :: for every Rem, which is weird and ugly

**Additional context**
Since by default Rems don't have any type, the default text will be plain text. Only if the user explicitly sets a type this takes effect. So this shouldn't cause any side effect/inconveniences for the current flow. I am not sure if this should be a bug or a feature request.

**Comment by mfranzs** [comment] 2020-10-07 01:09
We used to apply the formatting even when there was no :: icon. However, we discovered that this often created confusion around why certain Rem were bolded even though they had no obvious content. We'll be marking this as "working as intended" for now. if you want, you can apply the H3 heading to mark a Rem as bold.

**Closed by mfranzs** 2020-10-07 01:09 UTC
Labels: fixed-in-next-update
