### ISSUE TITLE
Hello, the picture in the local data has disappeared since the computer restarted

### ISSUE THREAD

**Issue by ben-1999** [remnoteio/remnote-issues#1116] opened 2021-04-15 02:09 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment] 2021-04-16 08:29
Hello @ben-1999 sorry to hear you are having issues, but this is an account specific issue and you will get the best response by sending an email to support@remnote.io. Closing this as it is not a bug.

**Closed by drkvj** 2021-04-16 08:29 UTC
