### ISSUE TITLE
Deleting Things Is Causing Remnote to Freeze

### ISSUE THREAD

**Issue by GarretD21** [remnoteio/remnote-issues#1169] opened 2021-05-04 19:16 UTC
**Describe the bug**

When I want to delete a document (Particularly ones that have references or tags), the program will freeze and a pop-up saying that the page has become unresponsive will appear. I won't be able to do anything after that, so I have to close out of Remnote and then open it back up. The things I wanted to delete don't delete when I restart the program though, so I'm just stuck with some different documents. 

When I want to delete things within a document, I noticed this same issue when I want to delete a portion that has references or tags linked to it.

**To Reproduce**
Go to my documents tab, right click on a document, and click on delete. Generally, it will freeze for a moment, then the pop-up saying the page is unresponsive will appear, and then I'll just have to close out of Remnote.

**Expected behavior**
I expected the program to just delete the document or portion of the document I wanted to delete without issue.

**Screenshots**
I don't know if this image upload worked, but basically it was just the pop-up on the screen saying on that the page is unresponsive.

![RemNote error](https://user-images.githubusercontent.com/77427865/117057464-5428c600-acd2-11eb-8440-a85dd364efeb.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: (For Chrome) 90.0.4430.93

**Additional context**
I think it mostly has to do with the things I want to delete having references or tags because everything I try to delete without them doesn't have this issue. This happens regardless of when I'm using the browser version of Remnote or the computer app.

**Comment by marcothesis** [comment] 2021-05-05 00:59
Duplicate of #1142

**Closed** 2021-06-04 03:55 UTC
Labels: bug, checked, data portability, fixed-in-next-update, fixed-in-remnote.1.3.13, priority=2
