### ISSUE TITLE
Sometimes delete button is not work

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#627] opened 2021-01-24 14:49 UTC
![image](https://user-images.githubusercontent.com/20538090/105633875-35619a80-5e6c-11eb-841d-7084986128db.png)
No matter how many times I press delete key on this text, it doesn't work.

Text is:
```
Hastalık
süresinin uzunluğu, komorbid psikiyatrik bozukluklar ve
ailede kaygı bozukluğu öyküsü, prognozu olumsuz etkilemektedir 
```

**Comment by mfranzs** [comment] 2021-01-24 19:39
Does this always happen with this text, or did this only happen once?

**Comment by Eikosa** [comment] 2021-01-24 19:48
sometimes, when I paste text, there is a virtual space at the beginning of the word, as shown in the picture. if that happens, the delete key doesn't work. and yes every time this problem occurs when i paste this text

could you please paste this text to remnote in this pdf to reproduce problem? (I couldn't think of any other way to send that text in exactly format)
![image](https://user-images.githubusercontent.com/20538090/105641641-2ee81880-5e96-11eb-9f0d-1d7f5fa5c2b5.png)
[Obsesif_Kompulsif_Bozuklukta_Gevşeme_Eğitimi_ve_Bilişsel_Davranışçı.pdf](https://github.com/remnoteio/remnote-issues/files/5863047/Obsesif_Kompulsif_Bozuklukta_Gevseme_Egitimi_ve_Bilissel_Davranisci.pdf)

**Comment by drkvj** [comment] 2021-04-16 11:22
I tried copying the exact sentence that you have asked, with the space before the first alphabet, I am still not able to reproduce this. If you are encountering this anywhere else again or if you are able to provide more detail for reproduction, kindly share with us so that we can try again, closing this until then.

**Closed by drkvj** 2021-04-16 11:22 UTC
Labels: cant-reproduce
