### ISSUE TITLE
Universal Descriptors function doesn't support non-latin characters

### ISSUE THREAD

**Issue by e0ns** [remnoteio/remnote-issues#38] opened 2020-08-12 00:19 UTC
When I define a universal descriptor which contains non-latin characters, it cannot be recognized as descriptor  in document (i.e. italic).

**Comment by mfranzs** [comment] 2020-08-12 05:00
Thanks for the report. Is the problem that it's not recognized as a descriptor because it doesn't start with a lowercase letter? You can manually set a Rem to a descriptor using the dropdown in the bottom toolbar or the `Ctrl + Alt + D` shortcut.

**Comment by e0ns** [comment] 2020-08-12 05:29
No, if you define a universal descriptor which is capitalized (in official tutorial),  it should automatically be recognized as descriptor. So, it's not about lowercase letter.

**Comment by e0ns** [comment] 2020-08-17 20:48
And the shortcut is conflict with show/hide dock on Mac.

**Comment by drkvj** [comment] 2021-04-08 17:37
This is not a bug, closing the report for now. Thanks!

**Closed by drkvj** 2021-04-08 17:37 UTC
Labels: cant-reproduce
