### ISSUE TITLE
Sometimes there is an unnecessary gap after creating a portal

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#308] opened 2020-11-27 20:51 UTC
- ![image](https://user-images.githubusercontent.com/20538090/100483765-12846580-310b-11eb-98bb-4ff96a688b23.png)
- ![image](https://user-images.githubusercontent.com/20538090/100483881-7149df00-310b-11eb-8b6f-72e054f6270f.png)

### **what should be**

--------------------------

- ![image](https://user-images.githubusercontent.com/20538090/100483822-3e075000-310b-11eb-8695-529ad388af26.png)
- ![image](https://user-images.githubusercontent.com/20538090/100483756-07313a00-310b-11eb-86ac-b1f4b6b67254.png)

**Comment by mfranzs** [comment] 2020-11-30 03:55
Thanks for the report. This is intentional to provide a way to add Rem after the portal; marking as working as intended for now.

**Closed by mfranzs** 2020-11-30 03:55 UTC

**Comment by hannesfrank** [comment] 2020-12-02 20:55
@Eikosa see https://forum.remnote.io/t/transparent-portals-aka-lightweight-transclusion-portal-simplifications/1029 for some discussion. The space can be removed with Custom CSS.

**Comment by Eikosa** [comment] 2020-12-09 17:50
I figured out how my problem occurred, i think this is not exactly what was wanted
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/20538090/101666952-cc5ec880-3a5f-11eb-998b-5e807f6f8dea.gif)
shouldn't there be a gap in the last portal only?
If there needs a space, after all, there is a bug in the same way.

**Comment by Eikosa** [comment] 2020-12-09 17:51
1. Add portals (at least 2-3 portal)
2. Move it like in the gif
3. See the problem

**Comment by Eikosa** [comment] 2020-12-09 17:52
Also when I reset the page, this problem is solved.
