### ISSUE TITLE
Search Portals do not correctly filter by "Document Status" not "Todo Status": Finished or Unfinished.

### ISSUE THREAD

**Issue by hugomarins** [remnoteio/remnote-issues#567] opened 2021-01-17 16:19 UTC
As far as I can see, it is not being possible to filter seraches by Document Status.

As you can see below, both my daily documents of 16th and 17th january have a "Finished" Status, and the others have a "Unfinished" status.
![image](https://user-images.githubusercontent.com/54500828/104848196-a3352180-58c2-11eb-8f21-00234dee5397.png)

![image](https://user-images.githubusercontent.com/54500828/104848301-1c347900-58c3-11eb-92a2-1798e3dbc327.png)

But when I try to filter by the status, nothing occurs; all of the documents are presented, no mather what status filter I used:

![image](https://user-images.githubusercontent.com/54500828/104848438-b5fc2600-58c3-11eb-8c57-7a5f076f1ff4.png)

The search for Todo status also does not work.

Thanks for the attention.

**Comment by tfiwm** [comment] 2021-01-17 17:56
You have to search for 'References' of 'Finished' (the child of 'Document'), not for 'Tags'. Check this screenshot for an example in which I filtered all daily documents that are in 'Finished' status. 
The rule of thumb is if what you want to filter is used as a tag then search for tag, otherwise search for its reference

![image](https://user-images.githubusercontent.com/24322880/104851428-cdc6b080-58a9-11eb-857d-f06b17d9e357.png)

**Comment by hugomarins** [comment] 2021-01-19 19:59
@tfiwm Thanks for teaching me. And is it possible to search for 2 arguments at the same time?

E.g. All the **unfinished todos** [using its reference] that have a certain **tag**, such as the name of the person the task is assigned to?

**Comment by drkvj** [comment] 2021-04-05 17:36
Hey @hugomarins ,@tfiwm taught you right. 

Additionally what you are asking for are advance search queries, they are one of the highest priority features at this point. I am looking forward to it myself ;) 

I will be closing this report now, as this is not a bug

**Closed by drkvj** 2021-04-05 17:36 UTC
